default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_user
  password: RailsPassword123!
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: jodis_list_api_development

test:
  <<: *default
  database: jodis_list_api_test

production:
  <<: *default
  database: jodis_list_api_production